#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.0.{build}.0
environment:
  gallery_api:
    secure: JQz0FeXP+JpPHxNu3Y99nqWVA8AwwG6FsahMJ8Pn7AlaDXILnp1UUUidaE4HahwI

install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo

# scripts to run before deployment
after_test:
    - ps: |
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorAfterTestTask

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
  - ps: |
        # The DscResource.Template has opt-out from any deploy task to PSGallery.
        # TODO: Opt-in to deploy tasks.
        Invoke-AppVeyorDeployTask -OptIn @()
